### ISSUE TITLE
Issue with version bound on sqlalchemy in pylegendmeta/setup.cfg

### ISSUE THREAD

**Issue by dcschaper** [legend-exp/pylegendmeta#18]
https://github.com/legend-exp/pylegendmeta/blob/4f9e8c6e3ba0a01b5eb05e5621a312db67cfd636/setup.cfg#L36

When attempting to create a new production environment for snakemake, the current syntax for the version bound on sqlalchemy breaks the build. If I replace (sqlachemy>=2.*) with (sqlalchemy>=2.0), pylegendmeta will build during the prodenv-install-sw step. Below is the output of the error that is produced when it is run with the unedited version bound.

```Processing ./software/python/src/pylegendmeta
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/anaconda3/bin/python3 /opt/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp98jnrc32
       cwd: /tmp/pip-req-build-0mdv02c_
  Complete output (52 lines):
  /tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/setuptools/config/setupcfg.py:520: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
    warnings.warn(msg, warning_class)
  Traceback (most recent call last):
    File "/tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 35, in __init__
      parsed = parse_requirement(requirement_string)
    File "/tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 64, in parse_requirement
      return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
    File "/tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 82, in _parse_requirement
      url, specifier, marker = _parse_requirement_details(tokenizer)
    File "/tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 126, in _parse_requirement_details
      marker = _parse_requirement_marker(
    File "/tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 147, in _parse_requirement_marker
      tokenizer.raise_syntax_error(
    File "/tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 163, in raise_syntax_error
      raise ParserSyntaxError(
  pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
      sqlalchemy>=2.*
                ~~~^
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/opt/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/opt/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 4, in <module>
    File "/tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
      _install_setup_requires(attrs)
    File "/tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 78, in _install_setup_requires
      dist.parse_config_files(ignore_option_errors=True)
    File "/tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 874, in parse_config_files
      self._finalize_requires()
    File "/tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 581, in _finalize_requires
      self._move_install_requirements_markers()
    File "/tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 621, in _move_install_requirements_markers
      inst_reqs = list(_reqs.parse(spec_inst_reqs))
    File "/tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3095, in __init__
      super(Requirement, self).__init__(requirement_string)
    File "/tmp/pip-build-env-jfpthkab/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
      raise InvalidRequirement(str(e)) from e
  pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
      sqlalchemy>=2.*
                ~~~^
```

**Comment by gipert** [comment]
Ciao Danielle, the reason why I had `2.*` and not `2.0` is that there were only pre-releases at that time. `>=2.0` would silently install `<2.0`. They literally released [2.0.0](https://pypi.org/project/SQLAlchemy/2.0.0/) four days ago, let me try to update `setup.cfg`.

**Comment by dcschaper** [comment]
I figured as much (that the asterisk was a placeholder). Thanks!

**Comment by gipert** [comment]
The actual reason is that pre-releases version hashes include letters (e.g. `2.0.0rc3`). In order to match these slugs with inequality operators one needs wildcards, which should in principle work in the container too and with any recent distribution of setuptools. I don't know why it fails.

**Comment by dcschaper** [comment]
Whoops, I intended wildcard, not placeholder. I also didn't know why it failed. I tried troubleshooting it before putting in an actual version number, but also couldn't figure it out. Thanks!
